
<?php include 'general/header.php';?>
        

<div class="clearfix"></div>

<div id="maincontent">
    <div id="maincontent-section1">
    <div class="listbox listbox-main news-box">
       <h1 style="text-align: center; color: red">Chào mừng quý vị và các bạn sinh viên đến với Ký túc xá
            thuộc trường Đại học Kỹ Thuật - Công Nghệ TP.Cần Thơ</h1>
            <p style="text-indent: 30px;text-align: justify;">Ký túc xá Bách khoa (KTXBK) toạ lạc ở số 497 đường Hoà Hảo, Phường 7, Quận 10, TP.HCM, cách Trường Đại Học Bách khoa (cơ sở 1 – 268 Lý Thường Kiệt, Q10) khoảng 1,5 km nơi mà quý vị và các bạn sẽ thường xuyên lui tới để tham gia học tập, nghiên cứu, nơi có nhiều tuyến xe buýt chạy qua, rất thuận tiện cho việc đi lại bằng các phương tiện khác nhau, do vậy KTXBK sẽ là ngôi nhà mơ ước của các sinh viên trường Đại học Bách khoa xa nhà khi học tập, nghiên cứu ở TP.HCM.</p>
            <p style="text-indent: 30px;text-align: justify;">Được thành lập từ năm 1978, sau nhiều năm sử dụng, KTXBK đã xuống cấp nghiêm trọng, do vậy năm 2004 KTXBK được nhà trường đầu tư xây mới và đưa vào sử dụng từ đầu năm 2009 với quy mô 12 tầng lầu và 01 tầng hầm để xe, tổng diện tích xây dựng khoảng 38.000 m2, mặt bằng khối có hình chữ U giật cấp thấp về phía đường Lý Thường Kiệt, bốn hướng tiếp cận các mặt đường chính (Hòa Hảo, Nguyễn Kim, Đào Duy Từ, Lý Thường Kiệt), do vậy các phòng ở đều được lấy ánh sáng và gió tự nhiên, đồng thời bố trí sân vườn bên trong ở giữa kết hợp cây xanh. Toàn bộ công trình có 03 vị trí thang máy với 06 thang loại 750 kg, 05 thang bộ và hệ thống PCCC, báo cháy tự động và hệ thống tạo áp thang thoát hiểm.</p>
     
               <p style="text-indent: 30px; margin-bottom: 10px;">Với hơn 400 phòng ở, làm việc, sinh hoạt theo thiết kế ban đầu, quý vị và các bạn có thể hình dung ra việc bố trí các loại phòng như sau:</p>
               <ul>
                  <li><b>Tầng 1:</b> Bố trí các phòng chức năng điều hành quản lý KTX, Thư viện, Phòng sinh hoạt chung dành cho các CLB, Đội, Nhóm, Nhà ăn dành cho sinh viên với diện tích 300 m2, Phòng Tập thể hình, Phòng tiếp khách SV 50 chỗ ngồi; Phòng Y tế; ……..Có 02 phòng khách với 12 chỗ dành cho thân nhân SV nội trú đến thăm và ở lại qua đêm khi cần.</li>
                  <li style="margin-top: 15px;"><b>Từ tầng 2 đến tầng 10:</b> Dành cho sinh viên Bách khoa diện ưu tiên (tổng cộng 2456 chỗ) Có 307 phòng (Loại phòng A1) , mỗi phòng 43 m2 bố trí 8 sinh viên Việt Nam lưu trú (04 giừơng tầng sắt), sân phơi quần áo và hệ thống Toilet khép kín trong phòng ở sinh viên.
      Mỗi sinh viên được trang bị: 01 tủ sắt đựng quần áo có móc khoá riêng, 01 bàn học liền kệ sách và có chỗ để máy vi tính khi cần, 01 ghế ngồi sắt nệm Hoà Phát, kệ để giày dép, như vậy khi sinh viên đến ở chỉ cần trang bị cá nhân gồm: mùng, mền, chiếu, gối mà thôi.
      Trong các phòng ở sinh viên được trang bị 7 bóng đèn các loại, 02 quạt trần và hệ thống nước được cấp thường trực 24/24 giờ và 01 bàn sinh hoạt chung, mỗi phòng còn được trang bị 01 máy điện thoại gọi nội bộ trong Ký túc xá miễn phí, đồng thời hệ thống cho phép nhận cuộc gọi từ bên ngoài vào tới các máy tại các phòng ở SV miễn phí, ngoài ra mỗi phòng còn được trang bị 01 ổ cắm ti vi truyền hình cáp.
      Mỗi tầng bố trí 01 phòng sinh hoạt chung để sinh viên học nhóm, hội họp sinh hoạt tập thể, xem Tivi truyền hình cáp.</li>
               <li style="margin-top: 15px;"><b>Tầng 11:</b> Gồm 20 phòng (Loại phòng A2), mỗi phòng 43 m2 dùng để bố trí sinh viên nước ngoài lưu trú với 04sv/phòng, sân phơi quần áo và hệ thống Toilet khép kín trong phòng ở. Mỗi phòng trang bị Tủ lạnh, nước nóng/lạnh, 04 giường cá nhân sắt nệm, 04 tủ sắt cá nhân có khoá riêng, 04 bàn học liền kệ sách và có chỗ để máy vi tính, 04 ghế ngồi sắt nệm Hoà Phát, kệ để giày dép và 01 bàn sinh hoạt chung.
      Trong các phòng ở được trang bị 7 bóng đèn các loại, 02 quạt trần và hệ thống nước nóng/lạnh được cấp thường trực 24/24 giờ, mỗi phòng còn được trang bị 01 máy điện thoại gọi nội bộ trong Ký túc xá miễn phí, đồng thời hệ thống cho phép nhận cuộc gọi từ bên ngoài vào tới các máy tại các phòng ở SV miễn phí, ngoài ra mỗi phòng còn được trang bị 01 ổ cắm ti vi truyền hình cáp, hệ thống internet Wifi miễn phí. Như vậy SV khi đến ở có thể ở được ngay mà không cần trang bị gì thêm.
     Tầng 11 bố trí 01 phòng sinh hoạt chung để sinh viên học nhóm, hội họp sinh hoạt tập thể, xem Tivi truyền hình cáp.</li>
                <li style="margin-top: 15px;"><b>Tầng 12:</b> Theo thiết kế, Nhà khách trường gồm 20 phòng (Loại phòng A3) với từ 2 đến 3 người/phòng, mỗi phòng 43 m2 dùng để bố trí chỗ ở cho các giáo sư, chuyên gia và các quý khách đến làm việc với nhà trường. Trang bị mỗi phòng gồm: từ 2 đến 3 giường cá nhân gỗ nệm, tủ gỗ treo áo quần, từ 2 đến 3bàn làm việc bằng gỗ + ghế nệm, bàn nước +  máy lạnh 2,5HP, tivi truyền hình cáp, tủ lạnh, hệ thống nước nóng/lạnh, sân phơi quần áo và hệ thống Toilet khép kín trong phòng ở, kệ để giày dép, ngoài ra còn có internet Wifi, điện thoại nội bộ sử dụng miễn phí…</li>
               </ul>
          <p style="text-indent: 30px; text-align: justify; margin-top: 15px;">KTXBK là đơn vị đầu tiên trong các Ký túc xá trên cả nước ứng dụng công nghệ thông tin trong việc cho sinh viên đăng ký thuê chỗ ở online và công bố kết quả xét duyệt thuê chỗ ở qua mạng internet và ứng dụng công nghệ thông tin trong công tác quản lý sinh viên, đồng thời cũng là đơn vị Ký túc xá đầu tiên thuê dịch vụ vệ sinh công nghiệp, dịch vụ  bảo vệ  chuyên nghiệp để bảo vệ Ký túc xá và sử dụng Hệ thống kiểm soát an ninh  bằng thẻ cảm ứng không tiếp xúc RFID để kiểm soát ra vào Ký túc xá và ứng dụng thẻ RFID trong Ký túc xá như đóng tiền Điện nước vượt định mức, mượn/trả sách thư viện, làm thủ tục thuê chỗ ở tại Ký túc xá Bách khoa, gởi xe, khám chữa bệnh tại Y tế Ký túc xá Bách khoa. </p>
          <p style="text-indent: 30px; text-align: justify; margin-top: 15px;">Với hệ thống mạng Internet Wifi phủ sóng khắp Ký túc xá và hệ thống internet cáp quang với các gói cước tốc độ cao tự chọn (20Mbps/20Mbps; 30Mbps/30Mbps) được lắp đặt đến từng phòng ở sinh viên với cước phí ưu đãi (246.5 00 đồng/tháng và 275.000 đồng/tháng).  </p>         
          <p style="text-indent: 30px; text-align: justify; margin-top: 15px;">Như vậy với vị trí địa lý thuận lợi, với thiết kế hiện đại, với trang thiết bị hoàn chỉnh, hệ thống an ninh chặt chẽ, hệ thống quản lý theo phương thức hiện đại, có thể nói KTXBK sánh ngang tầm các KTX tốt nhất của các nước trong khu vực Đông Nam Á và thế giới</p>
          <p style="text-indent: 30px; text-align: justify; margin-top: 15px;">Hy vọng quý vị và các bạn sẽ có những ngày tháng sống vui vẻ, thoả mái trong KTXBK, chúc quý vị và các bạn hạnh phúc và đạt được nhiều thành quả tốt đẹp trong công tác, học tập.</p>
    </div>
    <?php include 'general/slider.php';?>
        <?php include 'general/footer.php';?>